# Generated by Django 5.0.4 on 2024-04-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultados',
            name='cantidadNeg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultados',
            name='cantidadPos',
            field=models.IntegerField(default=0),
        ),
    ]
