# Generated by Django 5.0.4 on 2024-04-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapia',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
