# Generated by Django 5.0.4 on 2024-04-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
