# Generated by Django 5.0.4 on 2024-04-25 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_citamedica_fecha'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movimientosejercicios',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='terapia',
            name='cantidadTerapias',
        ),
        migrations.RemoveField(
            model_name='terapia',
            name='citaID',
        ),
        migrations.RemoveField(
            model_name='terapia',
            name='fecha',
        ),
        migrations.CreateModel(
            name='AsignarTerapias',
            fields=[
                ('AgigID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('citaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.citamedica')),
                ('terapiaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.terapia')),
            ],
        ),
    ]
