# Generated by Django 5.0.4 on 2024-04-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_movimientosejercicios_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movimientosejercicios',
            unique_together={('movimientoID', 'ejercicioID')},
        ),
    ]
