# Generated by Django 5.0.4 on 2024-04-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_movimientosejercicios_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientosejercicios',
            name='ejercicioID',
        ),
        migrations.AlterUniqueTogether(
            name='movimientosejercicios',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='movimientosejercicios',
            name='movimientoID',
        ),
        migrations.DeleteModel(
            name='Ejercicio',
        ),
        migrations.DeleteModel(
            name='MovimientosEjercicios',
        ),
    ]
